#!/usr/bin/env node
import {readJson,writeJson,buildNodeIndex,iterNodes,rootOf} from './lib/model.mjs';

const PROP=new Set(['REQUIRES','INVOKES','READS','WRITES','TRANSITIONS','EMITS','HANDLES','GUARANTEES','CONSTRAINED_BY','USES_PRIMITIVE','DERIVED_FROM']);
const DERIVED={rule:['human_projection','boundary_tests','scenario_tests','target_iir','generated_code'],behavior:['human_projection','scenario_tests','target_iir','generated_code'],decision:['human_projection','scenario_tests','target_iir','generated_code'],action:['human_projection','scenario_tests','target_iir','generated_code'],effect:['target_iir','generated_code','integration_tests'],state_machine:['human_projection','state_tests','target_iir','generated_code'],transition:['human_projection','state_tests','target_iir','generated_code'],constraint:['human_projection','property_tests','formal_projection'],invariant:['human_projection','property_tests','formal_projection'],scenario:['human_projection','scenario_tests'],primitive:['target_iir','generated_code','integration_tests'],entity:['human_projection','target_iir','generated_code'],enum:['human_projection','target_iir','generated_code','scenario_tests'],value_type:['human_projection','target_iir','generated_code','boundary_tests']};
function add(rev,target,source,reason){if(typeof target==='string'){(rev[target]??=[]).push([source,reason])}else if(Array.isArray(target))for(const x of target)add(rev,x,source,reason)}
function walkRefs(v,cb){if(Array.isArray(v))for(const x of v)walkRefs(x,cb);else if(v&&typeof v==='object'){if(typeof v.ref==='string')cb(v.ref);for(const x of Object.values(v))walkRefs(x,cb)}}
function build(doc){const root=rootOf(doc),nodes=buildNodeIndex(doc),rev={};for(const rel of root.relations??[])if(PROP.has(rel.relation))add(rev,rel.target,rel.source,`关系 ${rel.relation}`);for(const n of nodes.values()){const id=n.id;if(n.kind==='behavior'){add(rev,n.preconditions,id,'Behavior.preconditions');add(rev,n.flow,id,'Behavior.flow');add(rev,n.postconditions,id,'Behavior.postconditions')}if(n.kind==='decision'){walkRefs(n.when,r=>add(rev,r,id,'Decision.when'));add(rev,n.then,id,'Decision.then');add(rev,n.else,id,'Decision.else')}if(['action','foreach'].includes(n.kind)){add(rev,n.effects,id,'Action.effects');add(rev,n.do,id,'Foreach.do');walkRefs(n.when,r=>add(rev,r,id,'Action.when'))}if(n.kind==='state_machine')add(rev,n.transitions,id,'StateMachine.transitions');if(n.kind==='transition')add(rev,n.trigger,id,'Transition.trigger');if(n.kind==='scenario')add(rev,n.when,id,'Scenario.when');if(n.kind==='rule')walkRefs(n.expression,r=>add(rev,r,id,'Rule.expression'));}return {nodes,rev}}
const [file,...rest]=process.argv.slice(2);const oi=rest.indexOf('--output'),out=oi>=0?rest[oi+1]:null,changed=oi>=0?rest.slice(0,oi):rest;if(!file||!changed.length){console.error('usage: node analyze_impact.mjs model.json id... [--output file]');process.exit(2)}const doc=readJson(file),{nodes,rev}=build(doc),queue=changed.map(x=>[x,0]),seen=new Set(changed),affected=[],derived=new Set(),review=[];for(const id of changed){const n=nodes.get(id);if(n)for(const a of DERIVED[n.kind]??[])derived.add(a);else review.push({id,reason:'变化节点不在当前 CLM 中'})}while(queue.length){const [cur,d]=queue.shift();for(const [src,reason] of rev[cur]??[]){if(seen.has(src))continue;seen.add(src);affected.push({id:src,level:d===0?'DIRECT':'TRANSITIVE',reason,via:cur});const n=nodes.get(src);for(const a of DERIVED[n?.kind]??[])derived.add(a);queue.push([src,d+1])}}const result={changed,affected_nodes:affected,derived_artifacts:[...derived].sort(),review_candidates:review,revalidation:['clm_validator']};if(out)writeJson(out,result);else console.log(JSON.stringify(result,null,2));
