#!/usr/bin/env node
import {readJson,writeJson,rootOf,findNode,semanticHash} from './lib/model.mjs';
import fs from 'node:fs';

function getPath(obj,path){return path.split('.').reduce((x,k)=>x?.[k],obj)}
function setPath(obj,path,value){const ps=path.split('.');let cur=obj;for(const k of ps.slice(0,-1))cur=cur[k];cur[ps.at(-1)]=value}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}
function replaceRefs(v,oldRef,newRef){let n=0;if(Array.isArray(v)){for(let i=0;i<v.length;i++){if(v[i]===oldRef){v[i]=newRef;n++}else n+=replaceRefs(v[i],oldRef,newRef)}}else if(v&&typeof v==='object'){for(const k of Object.keys(v)){if(v[k]===oldRef){v[k]=newRef;n++}else n+=replaceRefs(v[k],oldRef,newRef)}}return n}
function applyOp(doc,op){const root=rootOf(doc);if(op.operation==='ADD_NODE'){root[op.collection]??=[];if(root[op.collection].some(x=>x.id===op.after?.id))throw new Error(`节点已存在: ${op.after?.id}`);root[op.collection].push(structuredClone(op.after));return}
if(['ADD_RELATION','REMOVE_RELATION'].includes(op.operation)){root.relations??=[];const rel={source:op.source,relation:op.relation,target:op.target};const i=root.relations.findIndex(x=>x.source===rel.source&&x.relation===rel.relation&&x.target===rel.target);if(op.operation==='ADD_RELATION'){if(i<0)root.relations.push(rel)}else{if(i<0)throw new Error('待移除关系不存在');root.relations.splice(i,1)}return}
const [collection,node]=findNode(doc,op.target_semantic_id);if(op.operation==='REMOVE_NODE'){root[collection]=root[collection].filter(x=>x.id!==op.target_semantic_id);return}
if(op.operation==='UPDATE_FIELD'){if(op.before!==undefined&&!same(getPath(node,op.field_path),op.before))throw new Error(`前置值不匹配: ${op.field_path}`);setPath(node,op.field_path,structuredClone(op.after));return}
if(['ADD_MEMBER','REMOVE_MEMBER'].includes(op.operation)){const arr=getPath(node,op.field_path??'value');if(!Array.isArray(arr))throw new Error('成员操作目标不是数组');const v=op.value??op.after,i=arr.findIndex(x=>same(x,v));if(op.operation==='ADD_MEMBER'){if(i<0)arr.push(structuredClone(v))}else{if(i<0)throw new Error('待移除成员不存在');arr.splice(i,1)}return}
if(op.operation==='REPLACE_REFERENCE'){const count=replaceRefs(node,op.before,op.after??op.value);if(!count)throw new Error(`未找到旧引用: ${op.before}`);return}
throw new Error(`不支持操作: ${op.operation}`)}

const [modelFile,changeFile,...args]=process.argv.slice(2);const out=args[args.indexOf('-o')+1]||args[args.indexOf('--output')+1],diffOut=args[args.indexOf('--diff-output')+1];if(!modelFile||!changeFile||!out){console.error('usage: node apply_change_set.mjs model.json change.json -o updated.json [--diff-output diff.json]');process.exit(2)}
try{const original=readJson(modelFile),csRaw=readJson(changeFile),cs=csRaw.semantic_change_set??csRaw,root=rootOf(original);if(cs.base_model_version!==undefined&&String(root.version)!==String(cs.base_model_version))throw new Error(`模型版本不匹配：期望 ${cs.base_model_version}，实际 ${root.version}`);const beforeHash=semanticHash(original);if(cs.base_semantic_hash&&cs.base_semantic_hash!==beforeHash)throw new Error(`语义哈希不匹配：期望 ${cs.base_semantic_hash}，实际 ${beforeHash}`);const working=structuredClone(original),changed=[];for(let i=0;i<(cs.operations??[]).length;i++){const op=cs.operations[i];try{applyOp(working,op)}catch(e){throw new Error(`第 ${i+1} 个操作失败（${op.operation}）：${e.message}`)}for(const x of [op.target_semantic_id,op.source,op.target,op.operation==='ADD_NODE'?op.after?.id:null])if(typeof x==='string')changed.push(x)}const afterHash=semanticHash(working);writeJson(out,working);const diff={change_set_id:cs.change_set_id,intent:cs.intent,behavior_change_level:cs.behavior_change_level,base_semantic_hash:beforeHash,result_semantic_hash:afterHash,changed_semantic_ids:[...new Set(changed)],verification_required:cs.verification_required??[]};if(diffOut)writeJson(diffOut,diff);else console.log(JSON.stringify(diff,null,2));}catch(e){console.error(JSON.stringify({ok:false,error:e.message},null,2));process.exit(1)}
