#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {readJson,writeJson} from './lib/model.mjs';

const pascal=(v)=>String(v??'Generated').split(/[^A-Za-z0-9]+/).filter(Boolean).map(x=>x[0].toUpperCase()+x.slice(1)).join('')||'Generated';
const digest=(s)=>crypto.createHash('sha256').update(s).digest('hex');
const useCaseName=(uc)=>`${pascal(uc.name??uc.semantic_refs?.[0]??uc.id)}UseCase`;

function validatePlan(root,uc,plan){
  const errors=[];
  if(plan.strategy!=='sqlite_transaction')errors.push(`不支持 transaction strategy: ${plan.strategy}`);
  if(root.target_profile?.transaction_scope!=='full_behavior')errors.push(`当前 transaction layer 只支持 full_behavior，实际 ${root.target_profile?.transaction_scope??'<missing>'}`);
  if(plan.boundary_valid!==true)errors.push(`transaction plan boundary_invalid: ${plan.id}`);
  const flow=(uc.steps??[]).map(x=>x.semantic_ref),members=plan.members??[];
  if(flow.length!==members.length||flow.some((x,i)=>x!==members[i]))errors.push(`full_behavior 要求 atomicity.members 完整覆盖 Behavior flow: ${plan.id}`);
  return errors;
}
function collectTransactional(root){
  const out=[];
  for(const uc of root.use_cases??[]){
    for(const planId of uc.transaction_plan_ids??[]){
      const plan=(root.transaction_plans??[]).find(x=>x.id===planId);
      if(!plan)throw new Error(`Use Case 引用不存在的 transaction plan: ${planId}`);
      const errors=validatePlan(root,uc,plan);if(errors.length)throw new Error(errors.join('; '));
      out.push({uc,plan});
    }
  }
  return out;
}
function source(root){
  const transactional=collectTransactional(root);if(!transactional.length)return{content:'',refs:[]};
  const lines=['// Code generated by logic-engineering. DO NOT EDIT.'];
  const imports=[...new Set(transactional.flatMap(({uc})=>[useCaseName(uc),`${useCaseName(uc)}Input`]))];
  lines.push(`import type { ${imports.join(', ')} } from '../usecases/generated.js';`,'');
  lines.push('export interface SqliteTransactionRunner {','  transaction<T>(work: () => Promise<T>): Promise<T>;','}','');
  for(const {uc,plan} of transactional){
    const base=useCaseName(uc),wrapper=`Transactional${base}`,input=`${base}Input`;
    lines.push(`export class ${wrapper} {`);
    lines.push(`  readonly transactionPlanId = ${JSON.stringify(plan.id)};`);
    lines.push(`  constructor(private readonly inner: Pick<${base}, 'execute'>, private readonly transactions: SqliteTransactionRunner) {}`,'');
    lines.push(`  async execute(input: ${input}): Promise<void> {`);
    lines.push('    await this.transactions.transaction(async () => {');
    lines.push('      await this.inner.execute(input);');
    lines.push('    });');
    lines.push('  }','}','');
  }
  return{content:lines.join('\n'),refs:transactional.flatMap(x=>[...(x.uc.semantic_refs??[]),...(x.plan.semantic_refs??[])])};
}
function testSource(root){
  const transactional=collectTransactional(root);if(!transactional.length)return'';
  const wrappers=transactional.map(({uc})=>`Transactional${useCaseName(uc)}`);
  const lines=['// Code generated by logic-engineering. DO NOT EDIT.','import { describe, expect, it } from "vitest";',`import { ${wrappers.join(', ')} } from '../transactions/generated.js';`,'','describe("generated transaction bindings", () => {'];
  for(const {uc} of transactional){
    const wrapper=`Transactional${useCaseName(uc)}`;
    lines.push(`  it(${JSON.stringify(`${uc.id} uses one transaction boundary`)}, async () => {`);
    lines.push('    let innerCalls = 0;');
    lines.push('    let transactionCalls = 0;');
    lines.push('    const inner = { execute: async () => { innerCalls += 1; } };');
    lines.push('    const transactions = { transaction: async <T>(work: () => Promise<T>): Promise<T> => { transactionCalls += 1; return work(); } };');
    lines.push(`    const useCase = new ${wrapper}(inner, transactions);`);
    lines.push('    await useCase.execute({} as never);');
    lines.push('    expect(transactionCalls).toBe(1);');
    lines.push('    expect(innerCalls).toBe(1);');
    lines.push('  });');
  }
  lines.push('});','');return lines.join('\n');
}
function addArtifact(manifest,generatedDir,rel,content,refs=[]){
  const file=path.join(generatedDir,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content,'utf8');
  manifest.artifacts=(manifest.artifacts??[]).filter(x=>x.path!==rel);
  manifest.artifacts.push({path:rel,semantic_refs:refs,generation_mode:'generated',content_hash:digest(content)});
}
function ensureTsconfig(manifest,generatedDir){
  const file=path.join(generatedDir,'tsconfig.json');if(!fs.existsSync(file))return;
  const config=readJson(file);config.include=[...new Set([...(config.include??[]),'transactions/**/*.ts'])];
  const content=JSON.stringify(config,null,2)+'\n';fs.writeFileSync(file,content,'utf8');
  const artifact=(manifest.artifacts??[]).find(x=>x.path==='tsconfig.json');if(artifact)artifact.content_hash=digest(content);
}

const [iirFile,generatedDir]=process.argv.slice(2);
if(!iirFile||!generatedDir){console.error('usage: node generate_typescript_transactions.mjs iir.json generated-ts-dir');process.exit(2);}
try{
  const doc=readJson(iirFile),root=doc.iir??doc,manifestFile=path.join(generatedDir,'manifest.json');
  if(!fs.existsSync(manifestFile))throw new Error('generated directory 缺少 manifest.json，请先运行 TypeScript base adapter');
  const manifest=readJson(manifestFile),tx=source(root);
  if(!tx.content){console.log(JSON.stringify({ok:true,generated:false,reason:'没有 transaction plan'},null,2));process.exit(0);}
  addArtifact(manifest,generatedDir,'transactions/generated.ts',tx.content,tx.refs);
  const tests=testSource(root);if(tests)addArtifact(manifest,generatedDir,'tests/generated.transaction.test.ts',tests,tx.refs);
  ensureTsconfig(manifest,generatedDir);
  manifest.generator_layers=[...new Set([...(manifest.generator_layers??[]),'typescript-transaction-v0.1'])];
  writeJson(manifestFile,manifest);
  console.log(JSON.stringify({ok:true,generated:true,transaction_plans:(root.transaction_plans??[]).length},null,2));
}catch(e){console.error(JSON.stringify({ok:false,error:e.message},null,2));process.exit(1);}
