#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {readJson,writeJson} from './lib/model.mjs';

function pascal(value){return String(value??'Generated').split(/[^A-Za-z0-9]+/).filter(Boolean).map(x=>x[0].toUpperCase()+x.slice(1)).join('')||'Generated';}
function camel(value){const p=pascal(value);return p[0].toLowerCase()+p.slice(1);}
function hash(content){return crypto.createHash('sha256').update(content).digest('hex');}
function blockers(root){return (root.unresolved??[]).filter(x=>typeof x==='string'||x?.blocking!==false);}
function put(root,rel,content,refs,artifacts){const file=path.join(root,rel);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,content,'utf8');artifacts.push({path:rel,semantic_refs:refs.filter(Boolean),generation_mode:'generated',content_hash:hash(content)});}
function methodName(op){const raw=typeof op==='string'?op:(op?.name??'execute');return camel(raw);}
function interfaceName(item){return pascal(item.name??item.id);}
function errorClass(ref){return `${pascal(String(ref).replace(/^error\./,''))}Error`;}

function portsSource(root){
  const lines=['// Code generated by logic-engineering. DO NOT EDIT.',''];
  for(const item of [...(root.repository_contracts??[]),...(root.external_ports??[])]){
    lines.push(`export interface ${interfaceName(item)} {`);
    for(const op of item.operations??['execute']) lines.push(`  ${methodName(op)}(): Promise<void>;`);
    lines.push('}','');
  }
  return lines.join('\n');
}

function errorsSource(root){
  const refs=[...new Set((root.error_mappings??[]).map(x=>x.semantic_error_ref??x.semantic_id??x.source).filter(x=>typeof x==='string'))];
  const lines=['// Code generated by logic-engineering. DO NOT EDIT.',''];
  for(const ref of refs){
    lines.push(`export class ${errorClass(ref)} extends Error {`);
    lines.push(`  readonly semanticId = ${JSON.stringify(ref)};`);
    lines.push('  constructor(message = '+JSON.stringify(ref)+') {');
    lines.push('    super(message);');
    lines.push(`    this.name = ${JSON.stringify(errorClass(ref))};`);
    lines.push('  }');
    lines.push('}','');
  }
  return lines.join('\n');
}

function usecasesSource(root){
  const contracts=new Map([...((root.repository_contracts??[]).map(x=>[x.id,interfaceName(x)])),...((root.external_ports??[]).map(x=>[x.id,interfaceName(x)]))]);
  const imports=[...new Set(contracts.values())];
  const lines=['// Code generated by logic-engineering. DO NOT EDIT.'];
  if(imports.length) lines.push(`import type { ${imports.join(', ')} } from '../ports/generated.js';`);
  lines.push('');
  for(const uc of root.use_cases??[]){
    const className=`${pascal(uc.name??uc.semantic_id??uc.id)}UseCase`;
    const deps=(uc.dependencies??[]).map(id=>({id,type:contracts.get(id)??'unknown',field:camel(id)}));
    lines.push(`export class ${className} {`);
    if(deps.length){
      const params=deps.map(d=>`private readonly ${d.field}: ${d.type}`).join(', ');
      lines.push(`  constructor(${params}) {}`);
    }else lines.push('  constructor() {}');
    lines.push('');
    lines.push('  async execute(): Promise<void> {');
    lines.push(`    // semantic: ${uc.semantic_id??uc.id}`);
    for(const g of uc.guards??[]) lines.push(`    // guard: ${JSON.stringify(g)}`);
    for(const s of uc.steps??[]) lines.push(`    // step: ${JSON.stringify(s)}`);
    lines.push(`    throw new Error(${JSON.stringify(`generated skeleton for ${uc.semantic_id??uc.id}: executable mapping pending`)});`);
    lines.push('  }','}','');
  }
  return lines.join('\n');
}

function testsSource(plan){
  const cases=(plan.target_test_plan??plan).cases??[];
  const lines=['// Code generated by logic-engineering. DO NOT EDIT.','import { describe, expect, it } from "vitest";','','describe("generated logic tests", () => {'];
  for(const c of cases){
    lines.push(`  it(${JSON.stringify(c.id)}, async () => {`);
    lines.push(`    // Given: ${JSON.stringify(c.given)}`);
    lines.push(`    // When: ${JSON.stringify(c.when)}`);
    lines.push(`    // Expect: ${JSON.stringify(c.expect)}`);
    lines.push(`    // Required fakes: ${JSON.stringify(c.fake_dependencies??[])}`);
    lines.push('    expect(true).toBe(true); // TODO: bind generated fixture and executable assertion');
    lines.push('  });');
  }
  lines.push('});','');
  return lines.join('\n');
}

function sqliteSource(root){
  const lines=['// Code generated by logic-engineering. DO NOT EDIT.','// SQLite adapter boundary. SQL is intentionally not guessed without explicit IIR mapping.',''];
  for(const repo of root.repository_contracts??[]) lines.push(`// TODO: bind ${repo.id} to an explicit SQLite table/column mapping.`);
  lines.push('');
  return lines.join('\n');
}

const [iirFile,testPlanFile,...args]=process.argv.slice(2);
const oi=args.indexOf('-o')>=0?args.indexOf('-o'):args.indexOf('--output-dir');
const output=oi>=0?args[oi+1]:null;
if(!iirFile||!testPlanFile||!output){console.error('usage: node generate_typescript.mjs iir.json target-test-plan.json -o generated-ts');process.exit(2);}

try{
  const iir=readJson(iirFile),plan=readJson(testPlanFile),root=iir.iir??iir;
  if(!['typescript','ts'].includes(String(root.target_profile?.language??'').toLowerCase())) throw new Error('Target Profile language 必须是 TypeScript');
  if(String(root.target_profile?.persistence??'').toLowerCase()!=='sqlite') throw new Error('首个 Reference Target persistence 必须是 SQLite');
  const unresolved=blockers(root); if(unresolved.length) throw new Error(`IIR 存在 blocking unresolved: ${JSON.stringify(unresolved)}`);
  fs.mkdirSync(output,{recursive:true}); const artifacts=[];
  const allPorts=[...(root.repository_contracts??[]),...(root.external_ports??[])];
  if(allPorts.length) put(output,'ports/generated.ts',portsSource(root),allPorts.map(x=>x.id),artifacts);
  put(output,'errors/generated.ts',errorsSource(root),(root.error_mappings??[]).map(x=>x.semantic_error_ref),artifacts);
  put(output,'usecases/generated.ts',usecasesSource(root),(root.use_cases??[]).map(x=>x.semantic_id),artifacts);
  put(output,'adapters/sqlite.ts',sqliteSource(root),(root.repository_contracts??[]).map(x=>x.id),artifacts);
  put(output,'tests/generated.test.ts',testsSource(plan),[],artifacts);
  const manifest={generator:'typescript-v0.1',source_clm:root.source_clm_id,source_semantic_hash:root.source_semantic_hash,iir_version:root.version,target_profile:root.target_profile?.id,artifacts};
  writeJson(path.join(output,'manifest.json'),manifest);
  console.log(JSON.stringify({ok:true,output_dir:output,artifacts:artifacts.length},null,2));
}catch(e){console.error(JSON.stringify({ok:false,error:e.message},null,2));process.exit(1);}
