#!/usr/bin/env python3
"""从 IIR v0.2 + Target Test Plan 生成 Go 代码骨架。"""
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path
from typing import Any, Dict, List


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))

def go_name(text: str) -> str:
    parts=re.split(r"[^A-Za-z0-9]+",text)
    return "".join(p[:1].upper()+p[1:] for p in parts if p) or "Generated"

def field_name(text: str) -> str:
    n=go_name(text)
    return n[:1].lower()+n[1:] if n else "dep"

def sha(text:str)->str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()

def write_artifact(root:Path, rel:str, content:str, semantic_refs:List[str], artifacts:List[Dict[str,Any]]):
    path=root/rel; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding="utf-8")
    artifacts.append({"path":rel,"semantic_refs":semantic_refs,"generation_mode":"generated","content_hash":sha(content)})

def unresolved(iir:Dict[str,Any])->List[Any]:
    root=iir.get("iir",iir)
    raw=root.get("unresolved",[]) or []
    out=[]
    for item in raw:
        if isinstance(item,dict) and item.get("blocking",True): out.append(item)
        elif isinstance(item,str): out.append(item)
    return out

def repository_code(repos:List[Dict[str,Any]])->str:
    lines=["// Code generated by logic-engineering. DO NOT EDIT.\n","package ports\n","import \"context\"\n"]
    for r in repos:
        name=go_name(r.get("name") or r.get("id","repository"))
        lines += [f"type {name} interface {{"]
        ops=r.get("operations",[]) or ["Save"]
        for op in ops:
            opname=go_name(op if isinstance(op,str) else op.get("name","Operation"))
            lines.append(f"\t{opname}(ctx context.Context) error")
        lines += ["}",""]
    return "\n".join(lines)+"\n"
def external_port_code(ports:List[Dict[str,Any]])->str:
    lines=["// Code generated by logic-engineering. DO NOT EDIT.\n","package ports\n","import \"context\"\n"]
    for p in ports:
        name=go_name(p.get("name") or p.get("id","external_port"))
        lines += [f"type {name} interface {{"]
        ops=p.get("operations",[]) or ["Execute"]
        for op in ops:
            opname=go_name(op if isinstance(op,str) else op.get("name","Operation"))
            lines.append(f"\t{opname}(ctx context.Context) error")
        lines += ["}",""]
    return "\n".join(lines)+"\n"
def error_code(mappings:List[Dict[str,Any]])->str:
    lines=["// Code generated by logic-engineering. DO NOT EDIT.\n","package usecase\n","import \"errors\"\n"]
    seen=set()
    for m in mappings:
        ref=m.get("semantic_error_ref") or m.get("semantic_id") or m.get("source")
        if not isinstance(ref,str): continue
        name="Err"+go_name(ref.replace("error.",""))
        if name in seen: continue
        seen.add(name); lines.append(f'var {name} = errors.New("{ref}")')
    return "\n".join(lines)+"\n"
def usecase_code(usecases:List[Dict[str,Any]])->str:
    chunks=["// Code generated by logic-engineering. DO NOT EDIT.\n","package usecase\n","import (\n\t\"context\"\n\t\"fmt\"\n)\n"]
    for u in usecases:
        sid=u.get("semantic_id") or u.get("implements") or u.get("id","usecase")
        name=go_name(u.get("name") or str(sid).replace("behavior.",""))+"UseCase"
        deps=u.get("dependencies",[]) or []
        chunks.append(f"type {name} struct {{")
        for d in deps:
            did=d if isinstance(d,str) else d.get("id","")
            chunks.append(f"\t{field_name(go_name(did))} any // {did}")
        chunks.append("}")
        chunks.append("")
        chunks.append(f"func (uc *{name}) Execute(ctx context.Context) error {{")
        chunks.append("\t_ = ctx")
        for guard in u.get("guards",[]) or []:
            chunks.append(f"\t// guard: {json.dumps(guard,ensure_ascii=False)}")
        for step in u.get("steps",[]) or []:
            chunks.append(f"\t// step: {json.dumps(step,ensure_ascii=False)}")
        chunks.append(f'\treturn fmt.Errorf("generated skeleton for {sid}: implementation binding required")')
        chunks.append("}")
        chunks.append("")
    return "\n".join(chunks)+"\n"
def tests_code(plan:Dict[str,Any])->str:
    root=plan.get("target_test_plan",plan)
    cases=root.get("tests",root.get("cases",[])) or []
    lines=["// Code generated by logic-engineering. DO NOT EDIT.\n","package tests\n","import (\n\t\"testing\"\n\t\"github.com/stretchr/testify/require\"\n)\n"]
    for c in cases:
        tid=c.get("id","generated_case")
        lines.append(f"func Test{go_name(tid)}(t *testing.T) {{")
        lines.append(f"\t// Given: {json.dumps(c.get('given'),ensure_ascii=False)}")
        lines.append(f"\t// When: {json.dumps(c.get('when'),ensure_ascii=False)}")
        lines.append(f"\t// Expect: {json.dumps(c.get('expect'),ensure_ascii=False)}")
        lines.append("\trequire.True(t, true) // TODO: bind generated fixture and assertions")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)+"\n"
def main()->int:
    p=argparse.ArgumentParser(description="IIR v0.2 → Go skeleton generator v0.1")
    p.add_argument("iir",type=Path); p.add_argument("target_tests",type=Path); p.add_argument("-o","--output-dir",type=Path,required=True)
    a=p.parse_args(); iir=load_json(a.iir); plan=load_json(a.target_tests); root=iir.get("iir",iir)
    lang=str((root.get("target_profile") or {}).get("language","")).lower()
    if lang!="go": print(json.dumps({"ok":False,"error":f"目标语言不是 Go: {lang}"},ensure_ascii=False)); return 1
    blockers=unresolved(iir)
    if blockers: print(json.dumps({"ok":False,"error":"IIR 存在 blocking unresolved","unresolved":blockers},ensure_ascii=False,indent=2)); return 1
    out=a.output_dir; out.mkdir(parents=True,exist_ok=True); artifacts=[]
    repos=root.get("repository_contracts",[]) or [] ; ports=root.get("external_ports",[]) or [] ; usecases=root.get("use_cases",[]) or [] ; errors=root.get("error_mappings",[]) or []
    if repos: write_artifact(out,"ports/repositories.go",repository_code(repos),[r.get("id","") for r in repos],artifacts)
    if ports: write_artifact(out,"ports/external.go",external_port_code(ports),[x.get("id","") for x in ports],artifacts)
    write_artifact(out,"usecase/usecases.go",usecase_code(usecases),[str(u.get("semantic_id") or u.get("id","")) for u in usecases],artifacts)
    write_artifact(out,"usecase/errors.go",error_code(errors),[str(e.get("semantic_error_ref") or e.get("semantic_id","")) for e in errors],artifacts)
    write_artifact(out,"tests/generated_test.go",tests_code(plan),[],artifacts)
    manifest={"generator":"go-v0.1","source_clm":root.get("source_clm_id"),"source_semantic_hash":root.get("source_semantic_hash"),"iir_version":root.get("version"),"target_profile":(root.get("target_profile") or {}).get("id"),"artifacts":artifacts}
    (out/"manifest.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"ok":True,"output_dir":str(out),"artifacts":len(artifacts)},ensure_ascii=False,indent=2)); return 0
if __name__=="__main__": raise SystemExit(main())
