#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {readJson,writeJson} from './lib/model.mjs';

const pascal=(v)=>String(v??'Generated').split(/[^A-Za-z0-9]+/).filter(Boolean).map(x=>x[0].toUpperCase()+x.slice(1)).join('')||'Generated';
const camel=(v)=>{const p=pascal(v);return p[0].toLowerCase()+p.slice(1)};
const prop=(v)=>{const p=String(v??'field').split(/[^A-Za-z0-9]+/).filter(Boolean);return p.length?p[0].toLowerCase()+p.slice(1).map(x=>x[0].toUpperCase()+x.slice(1)).join(''):'field'};
const digest=(s)=>crypto.createHash('sha256').update(s).digest('hex');
const methodName=(op)=>prop(typeof op==='string'?op:(op?.name??'execute'));
const interfaceName=(x)=>pascal(x.name??x.id);
const guardName=(ref)=>`guard${pascal(String(ref).replace(/^rule\./,''))}`;
const useCaseName=(uc)=>`${pascal(uc.name??uc.semantic_refs?.[0]??uc.id)}UseCase`;
const errorName=(ref)=>`${pascal(String(ref).replace(/^error\./,''))}Error`;
const quoteSql=(id)=>`"${String(id).replace(/"/g,'""')}"`;

function put(root,rel,content,refs,artifacts){const f=path.join(root,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,content,'utf8');artifacts.push({path:rel,semantic_refs:(refs??[]).filter(Boolean),generation_mode:'generated',content_hash:digest(content)});}
function maps(root){return{enums:new Map((root.domain_types?.enums??[]).map(x=>[x.semantic_ref,{...x,tsName:pascal(x.name??x.semantic_ref)}])),entities:new Map((root.domain_types?.entities??[]).map(x=>[x.semantic_ref,{...x,tsName:pascal(x.name??x.semantic_ref)}])),bindings:new Map((root.runtime_bindings??[]).map(x=>[x.semantic_ref,x]))};}
function tsType(ref,m){if(m.enums.has(ref))return m.enums.get(ref).tsName;if(m.entities.has(ref))return m.entities.get(ref).tsName;return{string:'string',boolean:'boolean',integer:'number',number:'number',datetime:'Date',date:'Date',duration:'number'}[ref]??'unknown';}
function parameterType(p,m){const base=tsType(p.type_ref,m);return p.cardinality==='many'?`${base}[]`:base;}
function access(ref,m,base='input'){const b=m.bindings.get(ref);if(!b)return`${base}[${JSON.stringify(ref)}]`;const slot=prop(b.slot);if(b.kind==='entity')return base?`${base}.${slot}`:slot;const tail=(b.path??[]).map(prop).join('.');return base?`${base}.${slot}.${tail}`:`${slot}.${tail}`;}
function scopedAccess(ref,m,scope=null,base='input'){if(scope?.alias&&typeof ref==='string'){if(ref===scope.alias)return scope.varName;if(ref.startsWith(`${scope.alias}.`)){const tail=ref.slice(scope.alias.length+1).split('.').filter(Boolean).map(prop).join('.');return tail?`${scope.varName}.${tail}`:scope.varName;}}return access(ref,m,base);}
function valueTs(v,m,base='input',scope=null){if(v==null)return'undefined';if(typeof v!=='object')return JSON.stringify(v);if(typeof v.ref==='string')return scopedAccess(v.ref,m,scope,base);if('literal'in v)return JSON.stringify(v.literal);if(v.enum)return JSON.stringify(v.enum.value);if(v.null)return'null';if(Array.isArray(v.set))return`[${v.set.map(x=>valueTs(x,m,base,scope)).join(', ')}]`;if(Array.isArray(v.list))return`[${v.list.map(x=>valueTs(x,m,base,scope)).join(', ')}]`;if(v.object&&typeof v.object==='object'){const fields=Object.entries(v.object.fields??{}).map(([ref,value])=>`${prop(String(ref).split('.').at(-1))}: ${valueTs(value,m,base,scope)}`);return`{ ${fields.join(', ')} }`;}return'undefined';}
function exprTs(e,m,base='input',scope=null){if(!e?.op)return'false';if(e.op==='all')return`(${(e.items??[]).map(x=>exprTs(x,m,base,scope)).join(' && ')||'true'})`;if(e.op==='any')return`(${(e.items??[]).map(x=>exprTs(x,m,base,scope)).join(' || ')||'false'})`;if(e.op==='not')return`!(${exprTs(e.item,m,base,scope)})`;const l=valueTs(e.left,m,base,scope),r=valueTs(e.right,m,base,scope);if(e.op==='in')return`${r}.includes(${l})`;if(e.op==='not_in')return`!${r}.includes(${l})`;return`${l} ${{eq:'===',ne:'!==',lt:'<',le:'<=',gt:'>',ge:'>='}[e.op]??'==='} ${r}`;}
function refsIn(v,out=new Set()){if(Array.isArray(v))for(const x of v)refsIn(x,out);else if(v&&typeof v==='object'){if(typeof v.ref==='string')out.add(v.ref);for(const x of Object.values(v))refsIn(x,out);}return out;}
function entityRefs(expr,m){const out=new Set();for(const ref of refsIn(expr)){const b=m.bindings.get(ref);if(b?.entity_ref)out.add(b.entity_ref);else if(b?.kind==='entity')out.add(ref);}return[...out];}
function fieldsByEntity(expr,m){const out=new Map();for(const ref of refsIn(expr)){const b=m.bindings.get(ref);if(b?.kind!=='field')continue;if(!out.has(b.entity_ref))out.set(b.entity_ref,new Set());out.get(b.entity_ref).add(prop((b.path??[]).at(-1)));}return out;}
function entityFieldAccess(fieldRef,m,entityVar='entity'){const b=m.bindings.get(fieldRef);const tail=(b?.path??[String(fieldRef).split('.').at(-1)]).map(prop).join('.');return `${entityVar}.${tail}`;}
function assertionMethod(value){return value!==null&&typeof value==='object'?'toEqual':'toBe';}

function domainSource(m){const l=['// Code generated by logic-engineering. DO NOT EDIT.',''];for(const e of m.enums.values())l.push(`export type ${e.tsName} = ${(e.values??[]).map(JSON.stringify).join(' | ')||'never'};`,'');for(const e of m.entities.values()){l.push(`export interface ${e.tsName} {`);for(const f of e.fields??[]){const base=tsType(f.type_ref,m),type=f.cardinality==='many'?`${base}[]`:base;l.push(`  ${prop(f.name)}${f.nullable?'?':''}: ${type}${f.nullable?' | null':''};`);}l.push('}','');}return l.join('\n');}
function portsSource(root,m){
  const types=[...new Set([...m.entities.values(),...m.enums.values()].map(x=>x.tsName))],l=['// Code generated by logic-engineering. DO NOT EDIT.'];if(types.length)l.push(`import type { ${types.join(', ')} } from '../domain/generated.js';`);l.push('');
  for(const r of root.repository_contracts??[]){const et=m.entities.get(r.entity_ref)?.tsName??'unknown';l.push(`export interface ${interfaceName(r)} {`);for(const op of r.operations??[])l.push(methodName(op)==='save'?`  save(entity: ${et}): Promise<void>;`:`  ${methodName(op)}(...args: unknown[]): Promise<unknown>;`);l.push('}','');}
  for(const p of root.external_ports??[]){l.push(`export interface ${interfaceName(p)} {`);for(const op of p.operations??[]){const params=(op.parameters??[]).map(x=>`${prop(x.name)}: ${parameterType(x,m)}`).join(', '),ret=op.return_type?tsType(op.return_type,m):'void';l.push(`  ${methodName(op)}(${params}): Promise<${ret}>;`);}l.push('}','');}
  return l.join('\n');
}
function errorsSource(root){const l=['// Code generated by logic-engineering. DO NOT EDIT.','export class GuardViolationError extends Error { constructor(readonly semanticId: string) { super(`guard failed: ${semanticId}`); this.name = "GuardViolationError"; } }',''];for(const ref of [...new Set((root.error_mappings??[]).map(x=>x.semantic_error_ref).filter(Boolean))])l.push(`export class ${errorName(ref)} extends Error { readonly semanticId = ${JSON.stringify(ref)}; constructor(message = ${JSON.stringify(ref)}) { super(message); this.name = ${JSON.stringify(errorName(ref))}; } }`,'');return l.join('\n');}
function rulesSource(root,m){const typeSet=new Set(),l=['// Code generated by logic-engineering. DO NOT EDIT.'];for(const uc of root.use_cases??[])for(const g of uc.guards??[])for(const er of entityRefs(g.expression,m)){const t=m.entities.get(er)?.tsName;if(t)typeSet.add(t);}if(typeSet.size)l.push(`import type { ${[...typeSet].join(', ')} } from '../domain/generated.js';`);l.push('');const emitted=new Set();for(const uc of root.use_cases??[])for(const g of uc.guards??[]){if(!g.semantic_ref||emitted.has(g.semantic_ref))continue;emitted.add(g.semantic_ref);const picks=fieldsByEntity(g.expression,m),parts=[];for(const er of entityRefs(g.expression,m)){const e=m.entities.get(er);if(!e)continue;const f=[...(picks.get(er)??[])],t=f.length?`Pick<${e.tsName}, ${f.map(JSON.stringify).join(' | ')}>`:e.tsName;parts.push(`${prop(e.slot)}: ${t}`);}l.push(`export function ${guardName(g.semantic_ref)}(input: { ${parts.join('; ')} }): boolean {`,`  return ${exprTs(g.expression,m)};`,'}','');}return l.join('\n');}

function effectLines(step,root,m,deps,indent,scope=null){const l=[];for(const effectId of step.effects??[]){const repo=(root.repository_contracts??[]).find(r=>(r.semantic_refs??[]).includes(effectId));if(repo){const d=deps.find(x=>x.id===repo.id),e=m.entities.get(repo.entity_ref);if(d&&e){const entityExpr=scope?.entityType===repo.entity_ref?scope.varName:`input.${prop(e.slot)}`;l.push(`${indent}await this.${d.field}.save(${entityExpr});`);}}const port=(root.external_ports??[]).find(p=>(p.semantic_refs??[]).includes(effectId));if(port){const d=deps.find(x=>x.id===port.id),op=(port.operations??[]).find(x=>(x.semantic_refs??[]).includes(effectId));if(d&&op){const args=(op.parameters??[]).map(x=>valueTs(x.value,m,'input',scope)).join(', ');l.push(`${indent}await this.${d.field}.${methodName(op)}(${args});`);}}}return l;}
function emitStep(step,root,m,deps,indent='    ',scope=null){const l=[];if(step.kind==='decision'){if(!step.when?.op)throw new Error(`Decision ${step.semantic_ref} 缺少 typed when expression`);l.push(`${indent}if (${exprTs(step.when,m,'input',scope)}) {`);for(const child of step.then_steps??[])l.push(...emitStep(child,root,m,deps,`${indent}  `,scope));if((step.else_steps??[]).length){l.push(`${indent}} else {`);for(const child of step.else_steps)l.push(...emitStep(child,root,m,deps,`${indent}  `,scope));}l.push(`${indent}}`);return l;}if(step.kind==='foreach'){if(!step.collection_ref||!step.item_alias||!step.item_type)throw new Error(`FOREACH_IIR_INCOMPLETE: ${step.semantic_ref}`);const itemVar=prop(step.item_alias),loopScope={alias:step.item_alias,varName:itemVar,entityType:step.item_type};l.push(`${indent}for (const ${itemVar} of ${access(step.collection_ref,m)}) {`);if(step.when?.op)l.push(`${indent}  if (!(${exprTs(step.when,m,'input',loopScope)})) continue;`);for(const child of step.do_steps??[])l.push(...emitStep(child,root,m,deps,`${indent}  `,loopScope));l.push(`${indent}}`);return l;}if(step.kind==='unresolved'||step.unresolved)throw new Error(`UNRESOLVED_STEP: ${step.semantic_ref}`);if(step.kind==='action'&&step.operation==='assign'&&step.target?.ref)l.push(`${indent}${scopedAccess(step.target.ref,m,scope)} = ${valueTs(step.value,m,'input',scope)};`);else if(step.operation&&!['assign','invoke'].includes(step.operation))throw new Error(`ACTION_OPERATION_NOT_SUPPORTED: ${step.semantic_ref} operation=${step.operation}`);l.push(...effectLines(step,root,m,deps,indent,scope));return l;}
function usecasesSource(root,m){const contracts=new Map([...((root.repository_contracts??[]).map(x=>[x.id,interfaceName(x)])),...((root.external_ports??[]).map(x=>[x.id,interfaceName(x)]))]),contractTypes=[...new Set(contracts.values())],entityTypes=[...new Set((root.use_cases??[]).flatMap(u=>(u.input_refs??[]).map(r=>m.entities.get(r)?.tsName).filter(Boolean)))],guards=[...new Set((root.use_cases??[]).flatMap(u=>(u.guards??[]).map(g=>guardName(g.semantic_ref))))],l=['// Code generated by logic-engineering. DO NOT EDIT.'];if(contractTypes.length)l.push(`import type { ${contractTypes.join(', ')} } from '../ports/generated.js';`);if(entityTypes.length)l.push(`import type { ${entityTypes.join(', ')} } from '../domain/generated.js';`);if(guards.length)l.push(`import { ${guards.join(', ')} } from '../rules/generated.js';`);l.push(`import { GuardViolationError } from '../errors/generated.js';`,'');for(const uc of root.use_cases??[]){const cls=useCaseName(uc),input=`${cls}Input`,deps=(uc.dependencies??[]).map(id=>({id,field:camel(id),type:contracts.get(id)??'unknown'}));l.push(`export interface ${input} {`);for(const er of uc.input_refs??[]){const e=m.entities.get(er);if(e)l.push(`  ${prop(e.slot)}: ${e.tsName};`);}l.push('}','',`export class ${cls} {`,deps.length?`  constructor(${deps.map(d=>`private readonly ${d.field}: ${d.type}`).join(', ')}) {}`:'  constructor() {}','',`  async execute(input: ${input}): Promise<void> {`);for(const g of uc.guards??[])l.push(`    if (!${guardName(g.semantic_ref)}(input)) throw new GuardViolationError(${JSON.stringify(g.semantic_ref)});`);for(const step of uc.steps??[])l.push(...emitStep(step,root,m,deps));l.push('  }','}','');}return l.join('\n');}

function defaultValue(typeRef,m,seed,cardinality='one'){if(cardinality==='many')return'[]';if(m.enums.has(typeRef))return JSON.stringify(m.enums.get(typeRef).values?.[0]??'');if(typeRef==='string')return JSON.stringify(`fixture-${seed}`);if(['integer','number','duration'].includes(typeRef))return'0';if(typeRef==='boolean')return'false';return'undefined as never';}
function fixtureLines(test,uc,m){const values=new Map(Object.entries(test.given??{}));for(const e of test.fixture_constraints??[]){if(e?.op==='eq'&&e.left?.ref&&e.right?.ref&&!values.has(e.left.ref)&&!values.has(e.right.ref)){const s=`fixture-${pascal(e.left.ref)}`;values.set(e.left.ref,s);values.set(e.right.ref,s);}}const out=[];for(const er of uc?.input_refs??[]){const e=m.entities.get(er);if(!e)continue;out.push(`const ${prop(e.slot)}: ${e.tsName} = {`);for(const f of e.fields??[]){const raw=values.get(f.semantic_ref),code=raw!==undefined?JSON.stringify(raw):defaultValue(f.type_ref,m,f.semantic_ref,f.cardinality);out.push(`  ${prop(f.name)}: ${code},`);}out.push('};');}return out;}
function fakeDeps(uc,root){const lines=[],args=[];for(const id of uc?.dependencies??[]){const name=camel(id);args.push(name);const c=(root.repository_contracts??[]).find(x=>x.id===id)??(root.external_ports??[]).find(x=>x.id===id);lines.push(`const ${name} = { ${(c?.operations??[]).map(op=>`${methodName(op)}: async (..._args: unknown[]) => undefined`).join(', ')} };`);}return{lines,args};}
function testsSource(root,plan,m){const cases=(plan.target_test_plan??plan).cases??[],guardFns=[...new Set(cases.filter(c=>c.target_kind==='guard').map(c=>guardName(c.target_id)))],ucNames=[...new Set(cases.filter(c=>c.target_kind==='use_case').map(c=>useCaseName((root.use_cases??[]).find(u=>u.id===c.use_case_id))).filter(x=>x!=='GeneratedUseCase'))],types=[...new Set([...m.entities.values(),...m.enums.values()].map(x=>x.tsName))],l=['// Code generated by logic-engineering. DO NOT EDIT.','import { describe, expect, it } from "vitest";'];if(types.length)l.push(`import type { ${types.join(', ')} } from '../domain/generated.js';`);if(guardFns.length)l.push(`import { ${guardFns.join(', ')} } from '../rules/generated.js';`);if(ucNames.length)l.push(`import { ${ucNames.join(', ')} } from '../usecases/generated.js';`);l.push('','describe("generated logic tests", () => {');for(const c of cases){if((c.unsupported??[]).length){l.push(`  it.todo(${JSON.stringify(`${c.id} — ${c.unsupported.join('; ')}`)});continue;}if(c.target_kind==='guard'){const uc=(root.use_cases??[]).find(u=>(u.guards??[]).some(g=>g.semantic_ref===c.target_id)),g=uc?.guards?.find(x=>x.semantic_ref===c.target_id),ers=entityRefs(g?.expression,m);l.push(`  it(${JSON.stringify(c.id)}, () => {`);for(const x of fixtureLines({given:c.given,fixture_constraints:[]},{input_refs:ers},m))l.push(`    ${x}`);l.push(`    expect(${guardName(c.target_id)}({ ${ers.map(r=>prop(m.entities.get(r)?.slot)).join(', ')} })).toBe(${JSON.stringify(c.expect?.rule_result)});`,'  });');continue;}if(c.target_kind==='use_case'){const uc=(root.use_cases??[]).find(u=>u.id===c.use_case_id);if(!uc){l.push(`  it.todo(${JSON.stringify(`${c.id} — missing use case`)});continue;}l.push(`  it(${JSON.stringify(c.id)}, async () => {`);for(const x of fixtureLines(c,uc,m))l.push(`    ${x}`);const f=fakeDeps(uc,root);for(const x of f.lines)l.push(`    ${x}`);l.push(`    const useCase = new ${useCaseName(uc)}(${f.args.join(', ')});`,`    await useCase.execute({ ${(uc.input_refs??[]).map(r=>prop(m.entities.get(r)?.slot)).join(', ')} });`);for(const [ref,val] of Object.entries(c.expect??{})){if(!m.bindings.has(ref))continue;const matcher=assertionMethod(val);l.push(`    expect(${access(ref,m,'')}).${matcher}(${JSON.stringify(val)});`);}l.push('  });');}}l.push('});','');return l.join('\n');}

function sqliteSource(root,m){const repos=(root.repository_contracts??[]).filter(r=>r.binding?.mapping),entityTypes=[...new Set(repos.map(r=>m.entities.get(r.entity_ref)?.tsName).filter(Boolean))],repoTypes=[...new Set(repos.map(interfaceName))],l=['// Code generated by logic-engineering. DO NOT EDIT.'];if(entityTypes.length)l.push(`import type { ${entityTypes.join(', ')} } from '../domain/generated.js';`);if(repoTypes.length)l.push(`import type { ${repoTypes.join(', ')} } from '../ports/generated.js';`);l.push('','export interface SqliteExecutor {','  run(sql: string, params: readonly unknown[]): Promise<void>;','}','');for(const repo of repos){const mapping=repo.binding.mapping,entity=m.entities.get(repo.entity_ref);if(!entity)throw new Error(`SQLITE_ENTITY_TYPE_MISSING: ${repo.entity_ref}`);const unsupported=(repo.operations??[]).map(methodName).filter(name=>name!=='save');if(unsupported.length)throw new Error(`SQLITE_REPOSITORY_OPERATION_NOT_SUPPORTED: ${repo.id} ${unsupported.join(',')}`);const columns=entity.fields.map(f=>({field:f.semantic_ref,column:mapping.columns?.[f.semantic_ref],expr:entityFieldAccess(f.semantic_ref,m,'entity')}));if(columns.some(x=>!x.column))throw new Error(`SQLITE_MAPPING_INCOMPLETE: ${repo.id}`);const pkField=mapping.primary_key,pk=columns.find(x=>x.field===pkField);if(!pk)throw new Error(`SQLITE_PRIMARY_KEY_MAPPING_MISSING: ${repo.id}`);const table=quoteSql(mapping.table),columnSql=columns.map(x=>quoteSql(x.column)).join(', '),placeholders=columns.map(()=>'?').join(', '),updates=columns.filter(x=>x.field!==pkField).map(x=>`${quoteSql(x.column)} = excluded.${quoteSql(x.column)}`),conflict=updates.length?`ON CONFLICT(${quoteSql(pk.column)}) DO UPDATE SET ${updates.join(', ')}`:`ON CONFLICT(${quoteSql(pk.column)}) DO NOTHING`,sql=`INSERT INTO ${table} (${columnSql}) VALUES (${placeholders}) ${conflict}`;l.push(`export class ${entity.tsName}SqliteRepository implements ${interfaceName(repo)} {`,`  constructor(private readonly db: SqliteExecutor) {}`,'',`  async save(entity: ${entity.tsName}): Promise<void> {`,`    await this.db.run(${JSON.stringify(sql)}, [`,`      ${columns.map(x=>x.expr).join(',\n      ')},`,'    ]);','  }','}','');}return l.join('\n')+'\n';}
const packageSource=()=>JSON.stringify({name:'logic-engineering-generated',private:true,type:'module',scripts:{typecheck:'tsc --noEmit',test:'vitest run'},devDependencies:{typescript:'^5.0.0',vitest:'^2.0.0'}},null,2)+'\n';
const tsconfigSource=()=>JSON.stringify({compilerOptions:{target:'ES2022',module:'NodeNext',moduleResolution:'NodeNext',strict:true,noEmit:true,skipLibCheck:true},include:['domain/**/*.ts','ports/**/*.ts','errors/**/*.ts','rules/**/*.ts','usecases/**/*.ts','adapters/**/*.ts','tests/**/*.ts']},null,2)+'\n';

const [iirFile,planFile,...args]=process.argv.slice(2),oi=args.indexOf('-o')>=0?args.indexOf('-o'):args.indexOf('--output-dir'),out=oi>=0?args[oi+1]:null;
if(!iirFile||!planFile||!out){console.error('usage: node generate_typescript_v02.mjs iir.json target-test-plan.json -o generated-ts');process.exit(2)}
try{const doc=readJson(iirFile),root=doc.iir??doc,plan=readJson(planFile),m=maps(root),blocking=(root.unresolved??[]).filter(x=>x?.severity==='blocking'||x?.blocking===true||typeof x==='string');if(!['typescript','ts'].includes(String(root.target_profile?.language??'').toLowerCase()))throw new Error('Target Profile language 必须是 TypeScript');if(String(root.target_profile?.persistence??'').toLowerCase()!=='sqlite')throw new Error('Reference Target persistence 必须是 SQLite');if(blocking.length)throw new Error(`IIR 存在 blocking unresolved: ${JSON.stringify(blocking)}`);fs.mkdirSync(out,{recursive:true});const artifacts=[];put(out,'domain/generated.ts',domainSource(m),[...m.enums.keys(),...m.entities.keys()],artifacts);put(out,'ports/generated.ts',portsSource(root,m),[...(root.repository_contracts??[]),...(root.external_ports??[])].map(x=>x.id),artifacts);put(out,'errors/generated.ts',errorsSource(root),(root.error_mappings??[]).map(x=>x.semantic_error_ref),artifacts);put(out,'rules/generated.ts',rulesSource(root,m),(root.use_cases??[]).flatMap(x=>(x.guards??[]).map(g=>g.semantic_ref)),artifacts);put(out,'usecases/generated.ts',usecasesSource(root,m),(root.use_cases??[]).map(x=>x.semantic_refs?.[0]),artifacts);put(out,'adapters/sqlite.ts',sqliteSource(root,m),(root.repository_contracts??[]).map(x=>x.id),artifacts);put(out,'tests/generated.test.ts',testsSource(root,plan,m),(plan.target_test_plan??plan).cases?.map(x=>x.source_semantic_id)??[],artifacts);put(out,'package.json',packageSource(),[],artifacts);put(out,'tsconfig.json',tsconfigSource(),[],artifacts);writeJson(path.join(out,'manifest.json'),{generator:'typescript-v0.2',source_clm:root.source_clm_id,source_semantic_hash:root.source_semantic_hash,iir_version:root.version,target_profile:root.target_profile?.id,artifacts});console.log(JSON.stringify({ok:true,output_dir:out,artifacts:artifacts.length,executable_tests:(plan.target_test_plan??plan).summary?.executable??0},null,2));}catch(e){console.error(JSON.stringify({ok:false,error:e.message},null,2));process.exit(1)}
