#!/usr/bin/env python3
"""从 IIR v0.2 + Target Test Plan 生成 TypeScript/Node.js 骨架。"""
from __future__ import annotations
import argparse, hashlib, json, re
from pathlib import Path
from typing import Any, Dict, List


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))

def pascal(text: str) -> str:
    parts=re.split(r"[^A-Za-z0-9]+",text)
    return "".join(p[:1].upper()+p[1:] for p in parts if p) or "Generated"
def camel(text: str) -> str:
    name=pascal(text); return name[:1].lower()+name[1:] if name else "value"
def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
def write(root: Path, rel: str, content: str, refs: List[str], artifacts: List[Dict[str,Any]]):
    path=root/rel; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(content,encoding="utf-8")
    artifacts.append({"path":rel,"semantic_refs":refs,"generation_mode":"generated","content_hash":sha(content)})
def blockers(iir: Dict[str,Any]) -> List[Any]:
    root=iir.get("iir",iir); out=[]
    for item in root.get("unresolved",[]) or []:
        if isinstance(item,dict) and item.get("blocking",True): out.append(item)
        elif isinstance(item,str): out.append(item)
    return out

def repository_code(repos):
    lines=["// Code generated by logic-engineering. DO NOT EDIT.\n"]
    for r in repos:
        name=pascal(r.get("name") or r.get("id","repository"))
        lines.append(f"export interface {name} {{")
        for op in r.get("operations",[]) or ["save"]:
            opname=camel(op if isinstance(op,str) else op.get("name","operation"))
            lines.append(f"  {opname}(): Promise<void>;")
        lines += ["}",""]
    return "\n".join(lines)
def external_code(ports):
    lines=["// Code generated by logic-engineering. DO NOT EDIT.\n"]
    for p in ports:
        name=pascal(p.get("name") or p.get("id","external_port"))
        lines.append(f"export interface {name} {{")
        for op in p.get("operations",[]) or ["execute"]:
            opname=camel(op if isinstance(op,str) else op.get("name","operation"))
            lines.append(f"  {opname}(): Promise<void>;")
        lines += ["}",""]
    return "\n".join(lines)
def error_code(errors):
    lines=["// Code generated by logic-engineering. DO NOT EDIT.\n"]
    for e in errors:
        ref=e.get("semantic_error_ref") or e.get("semantic_id") or e.get("source")
        if isinstance(ref,str):
            name=pascal(ref.replace("error.",""))+"Error"
            lines += [f"export class {name} extends Error {{",f"  readonly semanticId = {json.dumps(ref)};","}",""]
    return "\n".join(lines)
def usecase_code(usecases):
    chunks=["// Code generated by logic-engineering. DO NOT EDIT.\n"]
    for u in usecases:
        sid=str(u.get("semantic_id") or u.get("implements") or u.get("id","usecase"))
        name=pascal(u.get("name") or sid.replace("behavior.",""))+"UseCase"
        deps=u.get("dependencies",[]) or []
        params=[]
        for d in deps:
            did=d if isinstance(d,str) else d.get("id","")
            params.append(f"private readonly {camel(pascal(did))}: unknown /* {did} */")
        chunks.append(f"export class {name} {{")
        chunks.append(f"  constructor({', '.join(params)}) {{}}" if params else "  constructor() {}")
        chunks.append("  async execute(): Promise<void> {")
        for guard in u.get("guards",[]) or []: chunks.append(f"    // guard: {json.dumps(guard,ensure_ascii=False)}")
        for step in u.get("steps",[]) or []: chunks.append(f"    // step: {json.dumps(step,ensure_ascii=False)}")
        chunks.append(f"    throw new Error({json.dumps('generated skeleton for '+sid+': implementation binding required')});")
        chunks += ["  }","}",""]
    return "\n".join(chunks)
def tests_code(plan):
    root=plan.get("target_test_plan",plan); cases=root.get("tests",root.get("cases",[])) or []
    lines=['// Code generated by logic-engineering. DO NOT EDIT.','import { describe, expect, it } from "vitest";','', 'describe("generated logic tests", () => {']
    for c in cases:
        tid=c.get("id","generated_case")
        lines += [f"  it({json.dumps(tid)}, async () => {{",f"    // Given: {json.dumps(c.get('given'),ensure_ascii=False)}",f"    // When: {json.dumps(c.get('when'),ensure_ascii=False)}",f"    // Expect: {json.dumps(c.get('expect'),ensure_ascii=False)}","    expect(true).toBe(true); // TODO: bind fixture and assertions","  });"]
    lines += ["});",""]
    return "\n".join(lines)
def sqlite_adapter_code(repos):
    lines=['// Code generated by logic-engineering. DO NOT EDIT.','// SQLite adapter contracts only; table/column mappings require explicit IIR mapping.','']
    for r in repos:
        lines.append(f"// TODO: implement SQLite adapter for {r.get('id')}")
    return "\n".join(lines)+"\n"
def main()->int:
    p=argparse.ArgumentParser(description="IIR v0.2 → TypeScript skeleton generator v0.1")
    p.add_argument("iir",type=Path); p.add_argument("target_tests",type=Path); p.add_argument("-o","--output-dir",type=Path,required=True)
    a=p.parse_args(); iir=load_json(a.iir); plan=load_json(a.target_tests); root=iir.get("iir",iir)
    lang=str((root.get("target_profile") or {}).get("language","")).lower()
    if lang not in {"typescript","ts"}: print(json.dumps({"ok":False,"error":f"目标语言不是 TypeScript: {lang}"},ensure_ascii=False)); return 1
    persistence=str((root.get("target_profile") or {}).get("persistence","")).lower()
    if persistence!="sqlite": print(json.dumps({"ok":False,"error":f"首个参考目标要求 SQLite: {persistence}"},ensure_ascii=False)); return 1
    unresolved=blockers(iir)
    if unresolved: print(json.dumps({"ok":False,"error":"IIR 存在 blocking unresolved","unresolved":unresolved},ensure_ascii=False,indent=2)); return 1
    out=a.output_dir; out.mkdir(parents=True,exist_ok=True); artifacts=[]
    repos=root.get("repository_contracts",[]) or []; ports=root.get("external_ports",[]) or []; usecases=root.get("use_cases",[]) or []; errors=root.get("error_mappings",[]) or []
    if repos: write(out,"ports/repositories.ts",repository_code(repos),[r.get("id","") for r in repos],artifacts)
    if ports: write(out,"ports/external.ts",external_code(ports),[x.get("id","") for x in ports],artifacts)
    write(out,"usecases/generated.ts",usecase_code(usecases),[str(u.get("semantic_id") or u.get("id","")) for u in usecases],artifacts)
    write(out,"errors/generated.ts",error_code(errors),[str(e.get("semantic_error_ref") or e.get("semantic_id","")) for e in errors],artifacts)
    if repos: write(out,"adapters/sqlite.ts",sqlite_adapter_code(repos),[r.get("id","") for r in repos],artifacts)
    write(out,"tests/generated.test.ts",tests_code(plan),[],artifacts)
    manifest={"generator":"typescript-v0.1","source_clm":root.get("source_clm_id"),"source_semantic_hash":root.get("source_semantic_hash"),"iir_version":root.get("version"),"target_profile":(root.get("target_profile") or {}).get("id"),"artifacts":artifacts}
    (out/"manifest.json").write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    print(json.dumps({"ok":True,"output_dir":str(out),"artifacts":len(artifacts)},ensure_ascii=False,indent=2)); return 0
if __name__=="__main__": raise SystemExit(main())
