#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {readJson,writeJson,rootOf,iterNodes,buildNodeIndex,findNode,buildSymbolTable,semanticHash,unwrapValue,valueRef,valueType,compatibleTypes,enumContains,validatePlacement} from './lib/model.mjs';

const ROOT=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const SCHEMAS=path.join(ROOT,'schemas');
function die(message,extra={}){console.error(JSON.stringify({ok:false,error:message,...extra},null,2));process.exit(1)}
function arg(name,args){const i=args.indexOf(name);return i>=0?args[i+1]:null}
function has(name,args){return args.includes(name)}
function refsIn(v,out=[]){if(Array.isArray(v))for(const x of v)refsIn(x,out);else if(v&&typeof v==='object'){if(typeof v.ref==='string')out.push(v.ref);for(const x of Object.values(v))refsIn(x,out);}return out;}
function validateTypedValue(v,symbols,errors,owner,p){if(!v||typeof v!=='object'){errors.push({code:'INVALID_TYPED_VALUE',semantic_id:owner,path:p,message:'typed value 必须是对象'});return null;}const ks=['ref','literal','enum','null','set'].filter(k=>k in v);if(ks.length!==1){errors.push({code:'INVALID_TYPED_VALUE',semantic_id:owner,path:p,message:'必须且只能包含 ref/literal/enum/null/set 之一'});return null;}if(v.ref){if(!symbols[v.ref])errors.push({code:'UNKNOWN_SYMBOL',semantic_id:owner,path:p,message:`未知 symbol: ${v.ref}`});return symbols[v.ref]?.type??null;}if(v.enum){const t=v.enum.type;if(!symbols[t]||symbols[t].kind!=='enum')errors.push({code:'INVALID_ENUM_TYPE',semantic_id:owner,path:p,message:`非法 enum 类型: ${t}`});else if(!enumContains(symbols,t,v.enum.value))errors.push({code:'INVALID_ENUM_VALUE',semantic_id:owner,path:p,message:`${v.enum.value} 不属于 ${t}`});return t;}if(Array.isArray(v.set)){for(let i=0;i<v.set.length;i++)validateTypedValue(v.set[i],symbols,errors,owner,`${p}.set[${i}]`);return 'set';}return valueType(v,symbols);}
function validateExpr(e,symbols,errors,owner,p='expression'){if(!e||typeof e!=='object'){errors.push({code:'INVALID_TYPED_EXPRESSION',semantic_id:owner,path:p,message:'表达式必须是对象'});return;}const op=e.op;if(['all','any'].includes(op)){if(!Array.isArray(e.items)||!e.items.length)errors.push({code:'INVALID_TYPED_EXPRESSION',semantic_id:owner,path:p,message:`${op} 需要非空 items`});else e.items.forEach((x,i)=>validateExpr(x,symbols,errors,owner,`${p}.items[${i}]`));return;}if(op==='not'){return validateExpr(e.item,symbols,errors,owner,`${p}.item`)}if(!['eq','ne','lt','le','gt','ge','in','not_in'].includes(op)){errors.push({code:'INVALID_TYPED_EXPRESSION',semantic_id:owner,path:p,message:`不支持 op: ${op}`});return;}const lt=validateTypedValue(e.left,symbols,errors,owner,`${p}.left`);if(['in','not_in'].includes(op)){if(!e.right?.set)errors.push({code:'INVALID_TYPED_EXPRESSION',semantic_id:owner,path:`${p}.right`,message:'in/not_in 右侧必须是 set'});else for(let i=0;i<e.right.set.length;i++){const rt=validateTypedValue(e.right.set[i],symbols,errors,owner,`${p}.right.set[${i}]`);if(!compatibleTypes(lt,rt))errors.push({code:'TYPE_MISMATCH',semantic_id:owner,path:p,message:`集合成员类型 ${rt} 与 ${lt} 不兼容`});}return;}const rt=validateTypedValue(e.right,symbols,errors,owner,`${p}.right`);if(!compatibleTypes(lt,rt))errors.push({code:'TYPE_MISMATCH',semantic_id:owner,path:p,message:`比较类型 ${lt} 与 ${rt} 不兼容`});}
function validateClm(doc){const root=rootOf(doc),errors=[],warnings=[],ids=new Set(),symbols=buildSymbolTable(doc),index=buildNodeIndex(doc);for(const [c,n] of iterNodes(doc)){const pe=validatePlacement(n,c);if(pe)errors.push({code:'NODE_COLLECTION_MISMATCH',semantic_id:n.id,message:pe});if(ids.has(n.id))errors.push({code:'DUPLICATE_SEMANTIC_ID',semantic_id:n.id,message:'语义 ID 重复'});ids.add(n.id);for(const r of refsIn(n)){if(!symbols[r]&&!index.has(r)&&!r.startsWith('error.')&&!r.startsWith('event.')&&!r.startsWith('evidence.'))errors.push({code:'BROKEN_REFERENCE',semantic_id:n.id,message:`引用不存在: ${r}`});}for(const k of ['expression','when','guard','condition'])if(n[k]?.op)validateExpr(n[k],symbols,errors,n.id,k);if(n.kind==='action'&&n.operation==='assign'){const l=validateTypedValue(n.target,symbols,errors,n.id,'target'),r=validateTypedValue(n.value,symbols,errors,n.id,'value');if(!compatibleTypes(l,r))errors.push({code:'TYPE_MISMATCH',semantic_id:n.id,message:`赋值类型 ${l} 与 ${r} 不兼容`});}if(n.kind==='scenario'){for(const sec of ['given','then'])for(let i=0;i<(n[sec]??[]).length;i++){const a=n[sec][i],l=validateTypedValue(a.target,symbols,errors,n.id,`${sec}[${i}].target`),r=validateTypedValue(a.value,symbols,errors,n.id,`${sec}[${i}].value`);if(!compatibleTypes(l,r))errors.push({code:'TYPE_MISMATCH',semantic_id:n.id,message:`Scenario ${sec} 类型不兼容`});}for(const w of n.when??[])if(!index.has(w))errors.push({code:'BROKEN_REFERENCE',semantic_id:n.id,message:`Scenario when 引用不存在: ${w}`});}if(n.origin==='observed'&&!(n.evidence_refs??[]).length)errors.push({code:'MISSING_EVIDENCE',semantic_id:n.id,message:'observed 节点必须绑定证据'});}const trans=[...iterNodes(doc)].map(x=>x[1]).filter(n=>n.kind==='transition'),forbidden=new Set([...iterNodes(doc)].map(x=>x[1]).filter(n=>n.kind==='forbidden_transition').map(n=>`${n.from}->${n.to}`));for(const t of trans)if(forbidden.has(`${t.from}->${t.to}`))errors.push({code:'FORBIDDEN_TRANSITION_CONFLICT',semantic_id:t.id,message:`${t.from} → ${t.to} 同时允许和禁止`});return {valid:!errors.length,errors,warnings,stats:{nodes:ids.size,symbols:Object.keys(symbols).length}};}
function renderValue(v){const x=unwrapValue(v);if(x&&typeof x==='object'&&x.ref)return x.ref;if(Array.isArray(x))return x.map(y=>`“${y}”`).join('、');return String(x);}
function renderExpr(e){if(!e?.op)return String(e??'');if(e.op==='all')return e.items.map(renderExpr).join('，并且');if(e.op==='any')return e.items.map(renderExpr).join('，或者');if(e.op==='not')return `不满足（${renderExpr(e.item)}）`;const labels={eq:'等于',ne:'不等于',lt:'小于',le:'小于等于',gt:'大于',ge:'大于等于',in:'属于',not_in:'不属于'};return `${renderValue(e.left)}${labels[e.op]??e.op}${renderValue(e.right)}`;}
function renderHuman(doc){const r=rootOf(doc),idx=buildNodeIndex(doc),chunks=[`# ${r.name??r.id} — 人类可读逻辑`,''];for(const b of r.behaviors??[]){chunks.push(`## ${b.name??b.id}`,'',`标识：\`${b.id}\``);if((b.preconditions??[]).length){chunks.push('','### 前置条件');for(const x of b.preconditions){const n=idx.get(x);chunks.push(`- ${n?.expression?renderExpr(n.expression):x}。`);}}if((b.flow??[]).length){chunks.push('','### 处理过程');let i=1;for(const x of b.flow){const n=idx.get(x);let t=x;if(n?.kind==='action'&&n.operation==='assign')t=`将 ${renderValue(n.target)} 设置为 ${renderValue(n.value)}`;chunks.push(`${i++}. ${t}。`);}}chunks.push('');}for(const s of r.scenarios??[]){chunks.push(`## 场景：${s.name??s.id}`,'');for(const a of s.given??[])chunks.push(`- 已知：${renderValue(a.target)} = ${renderValue(a.value)}`);chunks.push(`- 当：${(s.when??[]).join('、')}`);for(const a of s.then??[])chunks.push(`- 则：${renderValue(a.target)} = ${renderValue(a.value)}`);chunks.push('');}return chunks.join('\n');}
function testVectors(doc){const root=rootOf(doc),idx=buildNodeIndex(doc),symbols=buildSymbolTable(doc),vectors=[];for(const n of idx.values()){if(n.kind==='rule'&&n.expression?.op&&['in','not_in'].includes(n.expression.op)){const subject=valueRef(n.expression.left),values=unwrapValue(n.expression.right);if(subject&&Array.isArray(values)){for(const v of values)vectors.push({id:`test.${n.id}.${v}`,source_semantic_id:n.id,kind:n.expression.op==='in'?'rule_positive':'rule_negative',given:{[subject]:v},when:null,expect:{rule_result:n.expression.op==='in'}});}}if(n.kind==='scenario'){const map=xs=>Object.fromEntries((xs??[]).map(a=>[valueRef(a.target),unwrapValue(a.value)]).filter(x=>x[0]));vectors.push({id:`test.${n.id}.example`,source_semantic_id:n.id,kind:'scenario',given:map(n.given),when:{behaviors:n.when??[]},expect:map(n.then)});}if(n.kind==='transition')vectors.push({id:`test.${n.id}.allowed`,source_semantic_id:n.id,kind:'state_transition',given:{state:n.from},when:{trigger:n.trigger},expect:{state:n.to}});}return {source_clm:root.id,test_vector_version:'0.2',vectors,warnings:[]};}
function compileIir(doc,profile){const root=rootOf(doc),idx=buildNodeIndex(doc),unresolved=[],repos=[],ports=[],useCases=[];const repoBy=new Map(),portBy=new Map();for(const e of root.effects??[]){if(['write','persist','read'].includes(e.kind)){const id=`repository.${String(e.resource??'resource').replace(/^domain\./,'').split('.')[0]}`;if(!repoBy.has(id))repoBy.set(id,{id,kind:'repository_contract',name:id.replace('repository.','')+' repository',semantic_refs:[],operations:[]});const r=repoBy.get(id);r.semantic_refs.push(e.id);r.operations.push(e.kind==='read'?'load':'save');}else if(['external_call','emit'].includes(e.kind)){const id=`port.${e.system??e.kind}`;if(!portBy.has(id))portBy.set(id,{id,kind:'external_port',name:e.system??e.kind,semantic_refs:[],operations:[]});const p=portBy.get(id);p.semantic_refs.push(e.id);p.operations.push(e.operation??(e.kind==='emit'?'publish':'execute'));}}repos.push(...repoBy.values());ports.push(...portBy.values());for(const b of root.behaviors??[]){const guards=(b.preconditions??[]).map(id=>({semantic_id:id,expression:idx.get(id)?.expression??null}));const steps=(b.flow??[]).map(id=>{const n=idx.get(id);if(!n){unresolved.push({semantic_id:id,kind:'missing_node',blocking:true});return {semantic_id:id,unresolved:true};}return {semantic_id:id,kind:n.kind,operation:n.operation,target:n.target,value:n.value,effects:n.effects??[],when:n.when,then:n.then,else:n.else};});const deps=[...repos.filter(r=>r.semantic_refs.some(x=>steps.some(s=>(s.effects??[]).includes(x)))).map(r=>r.id),...ports.filter(p=>p.semantic_refs.some(x=>steps.some(s=>(s.effects??[]).includes(x)))).map(p=>p.id)];useCases.push({id:`usecase.${b.id.replace('behavior.','')}`,semantic_id:b.id,name:b.name,kind:'use_case',guards,steps,dependencies:deps,failures:b.failures??[],postconditions:b.postconditions??[]});}return {iir:{version:'0.2',source_clm_id:root.id,source_clm_version:root.version,source_semantic_hash:semanticHash(doc),target_profile:profile,use_cases:useCases,repository_contracts:repos,external_ports:ports,transactions:[],concurrency_plans:[],retry_plans:[],idempotency_plans:[],error_mappings:(root.behaviors??[]).flatMap(b=>(b.failures??[]).map(e=>({semantic_error_ref:e}))),primitive_bindings:[],generation_regions:[{id:'generation.domain',mode:'generated'},{id:'generation.adapters',mode:'contract_or_handwritten'}],traceability:useCases.map(u=>({implementation_id:u.id,semantic_refs:[u.semantic_id]})),unresolved}};}
function validateIir(doc){const r=doc.iir??doc,errors=[];if(String(r.version)!=='0.2')errors.push({code:'IIR_VERSION',message:'IIR version 必须为 0.2'});const known=new Set([...(r.repository_contracts??[]),...(r.external_ports??[])].map(x=>x.id));for(const u of r.use_cases??[])for(const d of u.dependencies??[])if(!known.has(d))errors.push({code:'IIR_BROKEN_DEPENDENCY',message:`${u.id} 依赖不存在: ${d}`});for(const x of r.unresolved??[])if(typeof x==='string'||x?.blocking!==false)errors.push({code:'IIR_BLOCKING_UNRESOLVED',message:typeof x==='string'?x:x.semantic_id??x.kind});return {valid:!errors.length,errors,warnings:[]};}
function targetTests(vectors,iir){const r=iir.iir??iir,byBehavior=new Map((r.use_cases??[]).map(u=>[u.semantic_id,u]));const cases=(vectors.vectors??[]).map(v=>{const bs=v.when?.behaviors??[];const uc=bs.length?byBehavior.get(bs[0]):null;return {id:v.id,kind:v.kind,given:v.given,when:v.when,expect:v.expect,use_case_id:uc?.id??null,fake_dependencies:uc?.dependencies??[]};});return {target_test_plan:{version:'0.1',target_profile:r.target_profile?.id??null,source_clm:r.source_clm_id,cases,summary:{total:cases.length}}};}
function tsName(s){return String(s??'Generated').split(/[^A-Za-z0-9]+/).filter(Boolean).map(x=>x[0].toUpperCase()+x.slice(1)).join('')||'Generated'}
function generateTs(iir,plan,out){const r=iir.iir??iir;if(!['typescript','ts'].includes(String(r.target_profile?.language??'').toLowerCase()))throw new Error('目标语言不是 TypeScript');if(String(r.target_profile?.persistence??'').toLowerCase()!=='sqlite')throw new Error('首个参考目标要求 SQLite');const vr=validateIir(iir);if(!vr.valid)throw new Error(`IIR 不可生成: ${JSON.stringify(vr.errors)}`);fs.mkdirSync(out,{recursive:true});const artifacts=[];const put=(rel,c,refs=[])=>{const f=path.join(out,rel);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c);artifacts.push({path:rel,semantic_refs:refs,generation_mode:'generated',content_hash:crypto.createHash('sha256').update(c).digest('hex')});};let ports='// Code generated by logic-engineering. DO NOT EDIT.\n';for(const x of [...(r.repository_contracts??[]),...(r.external_ports??[])]){ports+=`export interface ${tsName(x.name??x.id)} {\n`;for(const op of x.operations??['execute'])ports+=`  ${String(op).replace(/[^A-Za-z0-9]/g,'')}(): Promise<void>;\n`;ports+='}\n\n';}put('ports/generated.ts',ports,[...(r.repository_contracts??[]),...(r.external_ports??[])].map(x=>x.id));let u='// Code generated by logic-engineering. DO NOT EDIT.\n';for(const x of r.use_cases??[]){u+=`export class ${tsName(x.name??x.semantic_id)}UseCase {\n  async execute(): Promise<void> {\n`;for(const g of x.guards??[])u+=`    // guard: ${JSON.stringify(g)}\n`;for(const s of x.steps??[])u+=`    // step: ${JSON.stringify(s)}\n`;u+=`    throw new Error(${JSON.stringify('generated skeleton for '+x.semantic_id)});\n  }\n}\n\n`;}put('usecases/generated.ts',u,(r.use_cases??[]).map(x=>x.semantic_id));let tests='// Code generated by logic-engineering. DO NOT EDIT.\nimport { describe, expect, it } from "vitest";\ndescribe("generated logic tests", () => {\n';for(const c of (plan.target_test_plan??plan).cases??[])tests+=`  it(${JSON.stringify(c.id)}, async () => {\n    // Given: ${JSON.stringify(c.given)}\n    // When: ${JSON.stringify(c.when)}\n    // Expect: ${JSON.stringify(c.expect)}\n    expect(true).toBe(true); // TODO bind fixture\n  });\n`;tests+='});\n';put('tests/generated.test.ts',tests);put('adapters/sqlite.ts','// SQLite adapter contracts only. Table/column mappings require explicit IIR mapping.\n',(r.repository_contracts??[]).map(x=>x.id));const manifest={generator:'typescript-v0.1',source_clm:r.source_clm_id,source_semantic_hash:r.source_semantic_hash,iir_version:r.version,target_profile:r.target_profile?.id,artifacts};writeJson(path.join(out,'manifest.json'),manifest);return manifest;}
function verifyManifest(dir){const m=readJson(path.join(dir,'manifest.json')),errors=[];for(const a of m.artifacts??[]){const f=path.join(dir,a.path);if(!fs.existsSync(f)){errors.push({code:'GENERATED_FILE_MISSING',path:a.path});continue;}const h=crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');if(h!==a.content_hash)errors.push({code:'GENERATED_FILE_DRIFT',path:a.path});}return {valid:!errors.length,errors};}
function applyPatch(doc,p){const out=structuredClone(doc),root=rootOf(out),op=p.semantic_patch??p;const [collection,node]=findNode(out,op.target_semantic_id);if(op.operation==='ADD_MEMBER'){const fp=op.field_path??'value',parts=fp.split('.');let cur=node;for(const k of parts)cur=cur[k];const v=op.value??op.after;if(!cur.some(x=>JSON.stringify(x)===JSON.stringify(v)))cur.push(v);}else if(op.operation==='UPDATE_FIELD'){const ps=op.field_path.split('.');let cur=node;for(const k of ps.slice(0,-1))cur=cur[k];cur[ps.at(-1)]=op.after;}else if(op.operation==='REMOVE_MEMBER'){const ps=(op.field_path??'value').split('.');let cur=node;for(const k of ps)cur=cur[k];const v=op.value??op.after;const i=cur.findIndex(x=>JSON.stringify(x)===JSON.stringify(v));if(i<0)throw new Error('待移除成员不存在');cur.splice(i,1);}else throw new Error(`Node CLI 暂不支持单 Patch 操作: ${op.operation}`);return out;}
function usage(){console.log('logic_cli.mjs <validate-clm|symbols|hash|render|test-vectors|compile-iir|validate-iir|target-tests|generate-ts|verify-manifest|pipeline> ...')}
const [cmd,...args]=process.argv.slice(2);try{
 if(cmd==='validate-clm'){const r=validateClm(readJson(args[0]));console.log(JSON.stringify(r,null,2));process.exit(r.valid?0:1)}
 if(cmd==='symbols'){writeJson(arg('-o',args)??arg('--output',args),{symbols:buildSymbolTable(readJson(args[0]))});}
 else if(cmd==='hash'){console.log(semanticHash(readJson(args[0])))}
 else if(cmd==='render'){const text=renderHuman(readJson(args[0]));const o=arg('-o',args)??arg('--output',args);if(o){fs.mkdirSync(path.dirname(o),{recursive:true});fs.writeFileSync(o,text)}else console.log(text)}
 else if(cmd==='test-vectors'){const r=testVectors(readJson(args[0]));const o=arg('-o',args)??arg('--output',args);o?writeJson(o,r):console.log(JSON.stringify(r,null,2))}
 else if(cmd==='compile-iir'){const doc=readJson(args[0]),profile=(readJson(args[1]).target_profile??readJson(args[1])),r=compileIir(doc,profile),o=arg('-o',args)??arg('--output',args);o?writeJson(o,r):console.log(JSON.stringify(r,null,2))}
 else if(cmd==='validate-iir'){const r=validateIir(readJson(args[0]));console.log(JSON.stringify(r,null,2));process.exit(r.valid?0:1)}
 else if(cmd==='target-tests'){const r=targetTests(readJson(args[0]),readJson(args[1])),o=arg('-o',args)??arg('--output',args);o?writeJson(o,r):console.log(JSON.stringify(r,null,2))}
 else if(cmd==='generate-ts'){const m=generateTs(readJson(args[0]),readJson(args[1]),arg('-o',args)??arg('--output-dir',args));console.log(JSON.stringify({ok:true,artifacts:m.artifacts.length},null,2))}
 else if(cmd==='verify-manifest'){const r=verifyManifest(args[0]);console.log(JSON.stringify(r,null,2));process.exit(r.valid?0:1)}
 else if(cmd==='pipeline'){const model=args[0],out=arg('--output-dir',args)??'.logic-engineering-output',profile=arg('--target-profile',args),patch=arg('--patch',args);fs.mkdirSync(out,{recursive:true});let doc=readJson(model);let vr=validateClm(doc);if(!vr.valid)die('CLM 校验失败',{validation:vr});if(patch){doc=applyPatch(doc,readJson(patch));writeJson(path.join(out,'updated.clm.json'),doc);vr=validateClm(doc);if(!vr.valid)die('修改后 CLM 校验失败',{validation:vr});}writeJson(path.join(out,'symbol-table.json'),{symbols:buildSymbolTable(doc)});fs.writeFileSync(path.join(out,'human-logic.md'),renderHuman(doc));const tv=testVectors(doc);writeJson(path.join(out,'test-vectors.json'),tv);let generated=null;if(profile){const iir=compileIir(doc,readJson(profile).target_profile??readJson(profile));writeJson(path.join(out,'implementation.iir.json'),iir);const iv=validateIir(iir);if(!iv.valid)die('IIR 校验失败',{validation:iv});const tp=targetTests(tv,iir);writeJson(path.join(out,'target-test-plan.json'),tp);if(has('--generate-ts',args)){generated=path.join(out,'generated-ts');generateTs(iir,tp,generated);const gm=verifyManifest(generated);if(!gm.valid)die('生成产物漂移',{validation:gm});}}console.log(JSON.stringify({ok:true,output_dir:out,generated_typescript:generated},null,2));}
 else {usage();process.exit(cmd?1:0)}
}catch(e){die(e.message,{stack:e.stack})}
